Repository bellshade/bellshade-monorepo, pull requests merged in 2022-03, with the labels that each got.

#24 feat: menambahkan file untuk code scanning
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#23 docs: memperbarui deskripsi dari route fastify
  .github/workflows/codeql-analysis.yml
  router/badge/index.js
  router/leaderboard/index.js
  router/learning/index.js
  router/main/index.js
Labels: documentation

#26 fix: menghilangkan `env` continous integration
  .github/workflows/publish.yml
Labels: bug

#28 docs(ningali): memperbaiki src gambar supaya bisa tampil di npm
  packages/ningali/README.md
Labels: documentation

#30 Update GH Action
  .github/workflows/cd.yml
Labels: chore
